### ISSUE TITLE
WhatsApp API is in wrong format and Rayon Persiapan Sains hasn't been included in the website

### ISSUE THREAD

**Issue by bukanvalen** [pmii1011/pmii1011.github.io#1]
Maaf Mas, bingung mau pakai judul issue Bahasa Inggris atau Bahasa Indonesia. Biar keren aku jadikan Inggris aja ya :v

Untuk yang masalah WhatsApp, sementara masih seperti ini
`https://wa.me/085733179537`

Nah harusnya kan angka 0 diganti jadi kode negara, kalau Indonesia kan 62
`https://wa.me/6285733179537`

Lalu untuk Rayon Sains, sepertinya memang belum ditambahkan ya Mas? Atau memang karena masih Rayon Persiapan jadi belum waktunya untuk dicantumkan? Terima kasih banyak sebelumnya

EDIT 1: Oh ya Mas, maaf lupa memberitahukan juga. Untuk yang email apakah benar `pmii1011e@gmail.com` atau `pmii1011@gmail.com`?

**Comment by Malikmal** [comment]
Sip, gpp bahasa indonesia

iya gk sempet saya lanjtukan, pada masa pembuatan ini masih 3 rayon. 
kalo mau lanjutkan nanti tak invite ke repository corenya. repo ini hanya hasil buildnya saja
dan juga sudah integrasi dengan cms wordpress di server lain.

paling gk bantu ubah nomor registrasi ke pengurus yg aktif sekarang lah 
sekaligus update beberapa informasi yng sudah tidak relevan
kalau bisa update postingan blognya lebih bagus lagi.

gimana @bukanvalen ?

**Comment by bukanvalen** [comment]
Boleh Mas, sekalian buat saya belajar juga. Terima kasih banyak sebelumnya

**Comment by Malikmal** [comment]
Check email atau notif github ya, dan accept invitationnya
ada 2 invitation, satunya member organization, satunya akses full ke repo corenya 
silahkan explore aja. klo ada yg mau ditanyakan bisa langsung WA aja
